# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: DIGG webbplats
    url: https://www.digg.se/
  - name: DIGG dataportal
    url: https://www.dataportal.se/
  - name: DIGG forum
    url: https://community.dataportal.se/
    __dangerous__body_down_if_text_present:
      - "har stängts ned"
    
  - name: DIGG webbriktlinjer
    url: https://webbriktlinjer.se/
  - name: RAÄ Kringla
    url: https://www.kringla.nu
  - name: RAÄ Kulturarvsdata Runor
    url: https://kulturarvsdata.se/uu/srdb/fab985d7-61cc-4014-9d85-0a5011d40dc8
  - name: Google
    url: https://www.google.com
  - name: Oswald
    url: https://oswald.wikibase.cloud/wiki/NOSAD-POC
  - name: OswaldSPARQLEndPoint
    url: https://oswald.wikibase.cloud/query/embed.html#%23%20https%3A%2F%2Fbeyond-notability.wikibase.cloud%2Fwiki%2FProject%3ASPARQL%2Fexamples%0APREFIX%20wd%3A%20%3Chttps%3A%2F%2Foswald.wikibase.cloud%2Fentity%2F%3E%0APREFIX%20wds%3A%20%3Chttps%3A%2F%2Foswald.wikibase.cloud%2Fentity%2Fstatement%2F%3E%0APREFIX%20wdv%3A%20%3Chttps%3A%2F%2Foswald.wikibase.cloud%2Fvalue%2F%3E%0APREFIX%20wdt%3A%20%3Chttps%3A%2F%2Foswald.wikibase.cloud%2Fprop%2Fdirect%2F%3E%0APREFIX%20p%3A%20%3Chttps%3A%2F%2Foswald.wikibase.cloud%2Fprop%2F%3E%0APREFIX%20ps%3A%20%3Chttps%3A%2F%2Foswald.wikibase.cloud%2Fprop%2Fstatement%2F%3E%0APREFIX%20pq%3A%20%3Chttps%3A%2F%2Foswald.wikibase.cloud%2Fprop%2Fqualifier%2F%3E%0A%23%202022-w42-7%0ASELECT%0A%3Fdt%20%3Fsess%20%3FsessLabel%20%3Fagenda%20%3Fstart%0A%3Fpres%20%3FpresLabel%20%3Forg%20%3ForgLabel%20%3Fspkr%20%3FspkrLabel%0A%23%20%3Ft%20%3Ft0%20%3Ftest%20%3Fvurl%20%3Fytid%0A%3Fvurl_t%20%3Fyturl_t%0AWHERE%20%7B%0A%20%20%3Fpres%20wdt%3AP12%20wd%3AQ157%20.%20%23%20a%20Presentation%0A%20%20OPTIONAL%7B%3Fpres%20wdt%3AP14%20%3Forg%20.%7D%0A%20%20OPTIONAL%7B%3Fpres%20wdt%3AP20%20%3Fsess%20.%7D%0A%20%20OPTIONAL%7B%3Fsess%20wdt%3AP22%20%3Fdt%20.%7D%0A%20%20OPTIONAL%7B%3Fpres%20wdt%3AP23%20%3Fstart%20.%7D%0A%20%20OPTIONAL%7B%3Fsess%20wdt%3AP16%20%3Fvurl%20.%7D%0A%20%20OPTIONAL%7B%3Fsess%20wdt%3AP21%20%3Fytid%20.%7D%0A%20%20OPTIONAL%7B%3Fpres%20wdt%3AP13%20%3Fspkr%20.%7D%0A%20%20OPTIONAL%7B%3Fsess%20wdt%3AP17%20%3Fagenda%20.%7D%0A%20%20%23%20BIND%20expressions%20referring%20to%20variables%20need%20to%20be%20outside%20OPTIONAL%20for%20some%20reason%3F%0A%20%20BIND%28COALESCE%28%3Fstart%2C%200%29%20AS%20%3Ft0%29.%0A%23%20%20%20BIND%28IF%28%3Ft0%20%3E%203000%2C%20%22late%22%2C%20%22early%22%29%20AS%20%3Ftest%29.%0A%20%20BIND%28IRI%28CONCAT%28STR%28%3Fvurl%29%2C%20IF%28%3Ft0%20%3E%200%2C%20CONCAT%28%22%23t%3D%22%2C%20STR%28%3Ft0%29%29%2C%20%22%22%29%29%29%20AS%20%3Fvurl_t%29%20.%0A%20%20BIND%28IRI%28CONCAT%28%22https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D%22%2C%20%3Fytid%2C%20IF%28%3Ft0%20%3E%200%2C%20CONCAT%28%22%23t%3D%22%2C%20STR%28%3Ft0%29%29%2C%20%22%22%29%29%29%20AS%20%3Fyturl_t%29%20.%0A%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Csv%2Cno%2Cen-gb%2Cen%22.%0A%20%20%7D%0A%7D%0AORDER%20BY%20DESC%28%3Fdt%29%20%3FsessLabel%20%28%21BOUND%28%3Fstart%29%29%20%3Fstart%20%3FpresLabel%0A%23GROUP%20BY%20%3FpLabel%20%3FvLabel%20%0A%23ORDER%20BY%20DESC%28%3Fcount%29
  - name: Riksarkivet NAD SE/ULA/12231
    url: https://sok.riksarkivet.se/?postid=ArkisRef%20SE/ULA/12231
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_present: *ra_error_texts
  - name: Riksarkivet forskarsalen
    url: https://sok.riksarkivet.se/digitala-forskarsalen
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_present: *ra_error_texts
  - name: Riksarkivet kyrkbok C0005418
    url: https://sok.riksarkivet.se/bildvisning/C0005418
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_present: *ra_error_texts
  - name: SCB - svensk-utbildningsnomenklatur-sun
    url: https://www.scb.se/dokumentation/klassifikationer-och-standarder/svensk-utbildningsnomenklatur-sun/
  - name: SCB - h6.scb.se/metadata/klassdb 
    url: https://www.h6.scb.se/metadata/klassdb.aspx
x-ra-error-texts: &ra_error_texts
  - "Webbplatsen går inte att besöka just nu"
  - "tekniska problem med webbplatsen"
  - "404 - File or directory not found"
  - "The resource you are looking for might have been removed"
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /salgo60/DiggUptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
